FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN pip3 install flask
RUN pip3 install requests
RUN apt-get install -y curl
RUN apt-get install -y vim
COPY app.py /app/app.py
WORKDIR /app
CMD ["python3", "app.py"]
